#!/bin/bash

if [ $# -eq 0 ]
then
	echo "Error de sintaxis hay que pasar la ip"
else
	devip=$(ping -c 1 $1 | egrep "100% packet loss")

	if [ "$devip" = "" ]
	then
		echo "Hay conexión con a ip"
	else
		echo "No hay conexión con la ip"
		sleep 5
	fi
fi
